events {
    worker_connections 1024;
}

http {

    limit_req_zone &binary_remote_addr zone=REQ_PER_IP:10m rate=10r/s;

    limit_req_zone &server_name zone=REQ_PER_SERVER:10m rate=1000r/s;

    

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        # index test.html;



        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        location ~* \.(env|log|conf|git|sql|sh) {
            deny all;
            return 404;
        }

        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always; 


        location /shorten {
            proxy_pass http://server:8080/shorten;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded_Port $server_port;
        }

        location ~ ^/([a-zA-Z0-9]+)$ {
            proxy_pass http://server:8080/$1;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded_Port $server_port;
        }

        # location / {
        #     try_files $uri $uri/ /test.html;
        # }


        
    }
}